# 🚗 RX Veículos - Docker Compose
# Para desenvolvimento local com Docker

version: '3.8'

services:
  # Aplicação RX Veículos
  rx-veiculos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env.local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rx-network

  # Nginx Reverse Proxy (opcional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - rx-veiculos
    restart: unless-stopped
    networks:
      - rx-network

networks:
  rx-network:
    driver: bridge

volumes:
  ssl_certs: 